### PR TITLE
Fixing casting Boolean Issue

### PR DESCRIPTION
**Pull request by malikhassan85**
I have applied the fix again after getting the latest changes from your master branch

### CODE REVIEW

**Comment by ErikEJ** [comment]
Available on myget feed: https://www.myget.org/gallery/ef7-sqlce

**Comment by malikhassan85** [comment]
Thanks Eric! we will check it and we will let you know if we have any issue.

**Comment by malikhassan85** [comment]
We have referenced the RC version on myget, everything is working as expected. I just wonder when you plan to publish the stable version from the package on nuget? We just want to know if it's worth referencing the RC version on myget, or we can wait for a a reasonable time and reference the stable one.

**Comment by ErikEJ** [comment]
You worry too much! 😄  - released to NuGet today

**Pull request merged**
